function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 30-May-2025 16:32:15

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','16x16, \theta_0 = -45°','Color',[0 0 1]);
set(plot1(2),'DisplayName','16x16, \theta_0 = -20°','Color',[1 0 0]);
set(plot1(3),'DisplayName','16x16, \theta_0 = 20°','Color',[0 1 0]);
set(plot1(4),'DisplayName','16x16, \theta_0 = 45°','Color',[1 0 1]);

% Create ylabel
ylabel('AF (dB)');

% Create xlabel
xlabel('Angle°');

% Create title
title('1D Beam Pattern with Amplitude (1-10) & Phase (±90°) Variation');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-90 90]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-20 0]);
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.716071428571429 0.0869047619047619 0.24702380952381 0.216269841269841]);

